import { useState, useEffect } from 'react';
import { useNavigate, useOutletContext } from 'react-router-dom';
import { getLocation, sortHospitalsByDistance, detectEmergencyNumber } from '../services/locationService';
import { formatMedicalSummaryForSharing, getConsentStatus, saveConsentStatus } from '../services/emergencyService';
import MapView from '../components/MapView';
import PillLoader from '../components/PillLoader';
import hospitals from '../data/hospitals';
import { translations } from '../data/translations';

const EmergencyPage = () => {
  const navigate = useNavigate();
  const { language } = useOutletContext();
  const t = translations[language].emergency;
  
  // State management
  const [stage, setStage] = useState('options'); // 'options' | 'calling' | 'finding' | 'map-view'
  const [userLocation, setUserLocation] = useState(null);
  const [nearestHospitals, setNearestHospitals] = useState([]);
  const [locationError, setLocationError] = useState(null);
  const [isLoadingLocation, setIsLoadingLocation] = useState(false);
  const [selectedHospital, setSelectedHospital] = useState(null);
  const [showConsentModal, setShowConsentModal] = useState(false);
  const [emergencyNumber, setEmergencyNumber] = useState(null);

  // Initialize emergency number on component mount
  useEffect(() => {
    const number = detectEmergencyNumber();
    setEmergencyNumber(number);
  }, []);

  // Handle call emergency services
  const handleCallEmergency = () => {
    setStage('calling');
    
    // Auto-dial after a short delay to show the calling screen
    setTimeout(() => {
      if (emergencyNumber) {
        window.location.href = `tel:${emergencyNumber.number}`;
      }
    }, 2000);
  };

  // Handle find hospitals
  const handleFindHospitals = async () => {
    setStage('finding');
    setIsLoadingLocation(true);
    setLocationError(null);

    try {
      const locationResult = await getLocation();
      
      if (locationResult.success) {
        setUserLocation(locationResult.data);
        
        // Sort hospitals by distance
        const sortedHospitals = sortHospitalsByDistance(locationResult.data, hospitals);
        setNearestHospitals(sortedHospitals);
        
        setStage('map-view');
      } else {
        setLocationError(locationResult.error);
        // Still show hospitals but without distance sorting
        setNearestHospitals(hospitals);
        setStage('map-view');
      }
    } catch (error) {
      console.error('Error finding hospitals:', error);
      setLocationError(t.locationError);
      setNearestHospitals(hospitals);
      setStage('map-view');
    } finally {
      setIsLoadingLocation(false);
    }
  };

  // Handle hospital selection
  const handleHospitalSelect = (hospital) => {
    setSelectedHospital(hospital);
  };

  // Handle medical summary sharing
  const handleShareMedicalSummary = () => {
    const consent = getConsentStatus();
    if (consent.granted) {
      // Show summary directly
      showMedicalSummary();
    } else {
      // Show consent modal
      setShowConsentModal(true);
    }
  };

  // Show medical summary
  const showMedicalSummary = () => {
    const summaryResult = formatMedicalSummaryForSharing();
    if (summaryResult.success) {
      // Create a new window/tab with the summary
      const summaryWindow = window.open('', '_blank');
      summaryWindow.document.write(`
        <html>
          <head>
            <title>${t.medicalSummary}</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; background-color: #0f172a; color: #e2e8f0; }
              pre { white-space: pre-wrap; word-wrap: break-word; background-color: #1e293b; padding: 20px; border-radius: 8px; border: 1px solid #334155; }
              .header { color: #ef4444; font-weight: bold; margin-bottom: 20px; font-size: 24px; text-align: center; }
              .disclaimer { background: #451a03; border: 1px solid #78350f; color: #fdba74; padding: 15px; border-radius: 5px; margin-top: 20px; font-size: 14px; }
            </style>
          </head>
          <body>
            <div class="header">EMERGENCY MEDICAL SUMMARY</div>
            <pre>${summaryResult.data}</pre>
            <div class="disclaimer">
              <strong>DISCLAIMER:</strong> This summary is generated by AI based on previously uploaded medical reports. It is intended to assist medical professionals but should not replace clinical assessment.
            </div>
          </body>
        </html>
      `);
    } else {
      alert('No medical summary available. Please analyze a medical report first.');
    }
  };

  // Handle consent confirmation
  const handleConsentConfirm = () => {
    saveConsentStatus(true);
    setShowConsentModal(false);
    showMedicalSummary();
  };

  // Render options screen (Stage 1)
  const renderOptionsScreen = () => (
    <div className="min-h-screen bg-slate-900 py-12 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
      {/* Background Elements */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-red-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl animate-pulse delay-1000"></div>
      </div>

      <div className="max-w-4xl mx-auto relative z-10">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-6">
            🚨 Emergency Assistance
          </h1>
          <p className="text-xl text-slate-400 mb-8">
            Get immediate help when you need it most
          </p>
        </div>

        {/* Option Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Call Emergency Services Card */}
          <div 
            className="bg-slate-800/50 backdrop-blur-md border border-white/10 rounded-2xl shadow-2xl p-8 hover:shadow-red-500/20 transition-all duration-300 cursor-pointer hover:-translate-y-2 group"
            onClick={handleCallEmergency}
          >
            <div className="text-center">
              <div className="w-20 h-20 mx-auto mb-4 bg-red-500/20 rounded-full flex items-center justify-center group-hover:bg-red-500/30 transition-colors">
                <svg 
                  className="w-10 h-10 text-red-500" 
                  fill="none" 
                  strokeLinecap="round" 
                  strokeLinejoin="round" 
                  strokeWidth="2" 
                  viewBox="0 0 24 24" 
                  stroke="currentColor"
                >
                  <path d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                </svg>
              </div>
              <h2 className="text-2xl font-bold text-white mb-3">{t.callEmergencyServices}</h2>
              <p className="text-slate-400 mb-6">
                {t.callEmergencyDesc} ({emergencyNumber?.displayText || '112/911'})
              </p>
              <button 
                onClick={handleCallEmergency}
                className="bg-red-600 text-white px-8 py-3 rounded-full font-bold hover:bg-red-700 transition-all duration-300 shadow-lg shadow-red-600/30"
              >
                {t.callNow}
              </button>
            </div>
          </div>

          {/* Find Nearest Hospital Card */}
          <div 
            className="bg-slate-800/50 backdrop-blur-md border border-white/10 rounded-2xl shadow-2xl p-8 hover:shadow-blue-500/20 transition-all duration-300 cursor-pointer hover:-translate-y-2 group"
            onClick={handleFindHospitals}
          >
            <div className="text-center">
              <div className="w-20 h-20 mx-auto mb-4 bg-blue-500/20 rounded-full flex items-center justify-center group-hover:bg-blue-500/30 transition-colors">
                <svg 
                  className="w-10 h-10 text-blue-500" 
                  fill="none" 
                  strokeLinecap="round" 
                  strokeLinejoin="round" 
                  strokeWidth="2" 
                  viewBox="0 0 24 24" 
                  stroke="currentColor"
                >
                  <path d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                  <path d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
              </div>
              <h2 className="text-2xl font-bold text-white mb-3">{t.findHospitals}</h2>
              <p className="text-slate-400 mb-6">
                {t.findHospitalDesc}
              </p>
              <button 
                onClick={handleFindHospitals}
                className="bg-blue-600 text-white px-8 py-3 rounded-full font-bold hover:bg-blue-700 transition-all duration-300 shadow-lg shadow-blue-600/30"
              >
                {t.findHospitalsBtn}
              </button>
            </div>
          </div>
        </div>

        {/* Back to Home */}
        <div className="text-center mt-12">
          <button
            onClick={() => navigate('/')}
            className="text-slate-400 hover:text-white transition-colors duration-300 flex items-center justify-center gap-2 mx-auto"
          >
            <span>←</span> {t.backToHome}
          </button>
        </div>
      </div>
    </div>
  );

  // Render calling screen (Stage 2)
  const renderCallingScreen = () => (
    <div className="min-h-screen bg-slate-900 py-12 px-4 sm:px-6 lg:px-8 flex items-center justify-center relative overflow-hidden">
      {/* Background Pulse */}
      <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-red-600/20 rounded-full blur-3xl animate-pulse"></div>

      <div className="max-w-md mx-auto text-center relative z-10">
        <div className="bg-slate-800/50 backdrop-blur-md border border-white/10 rounded-2xl shadow-2xl p-8">
          <div className="animate-pulse mb-8">
            <div className="w-24 h-24 mx-auto bg-red-500/20 rounded-full flex items-center justify-center">
              <svg 
                className="w-12 h-12 text-red-500" 
                fill="none" 
                strokeLinecap="round" 
                strokeLinejoin="round" 
                strokeWidth="2" 
                viewBox="0 0 24 24" 
                stroke="currentColor"
              >
                <path d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
              </svg>
            </div>
          </div>
          
          <h2 className="text-3xl font-bold text-white mb-4">{t.emergencyServicesTitle || t.title}</h2>
          
          <div className="text-6xl font-bold text-red-500 mb-8">
            {emergencyNumber?.number || '112'}
          </div>
          
          <p className="text-slate-400 mb-6">
            {t.tapToCall}
          </p>
          
          <a
            href={`tel:${emergencyNumber?.number || '112'}`}
            className="bg-red-600 text-white px-8 py-4 rounded-full font-bold hover:bg-red-700 transition-all duration-300 shadow-lg shadow-red-600/30 text-lg inline-block w-full"
          >
            📞 {t.callPrefix} {emergencyNumber?.number || '112'}
          </a>
          
          <div className="mt-8 pt-6 border-t border-white/10">
            <button
              onClick={() => setStage('options')}
              className="text-slate-400 hover:text-white transition-colors duration-300"
            >
              {t.cancelCall}
            </button>
          </div>
        </div>
      </div>
    </div>
  );

  // Render finding hospitals screen (Stage 3)
  const renderFindingScreen = () => {
    let loadingText = t.findingHospitalsText;
    
    if (isLoadingLocation) {
      loadingText = t.gettingLocation;
    } else if (locationError) {
      loadingText = t.loadingHospitalData;
    }
    
    return <PillLoader text={loadingText} />;
  };

  // Render map view with hospital list (Stage 4)
  const renderMapView = () => (
    <div className="min-h-screen bg-slate-900 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">{t.nearbyHospitalsTitle}</h1>
          <p className="text-slate-400">
            {userLocation ? 
              t.foundHospitals.replace('{count}', nearestHospitals.length) : 
              t.showingHospitals.replace('{count}', nearestHospitals.length)
            }
          </p>
        </div>

        {/* Map and Hospital List Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Map Section (2/3 width on desktop) */}
          <div className="lg:col-span-2">
            <MapView
              userLocation={userLocation}
              hospitals={nearestHospitals.slice(0, 15)} // Limit to 15 for performance
              onHospitalSelect={handleHospitalSelect}
              selectedHospital={selectedHospital}
              className="h-96 lg:h-[600px] rounded-xl overflow-hidden border border-white/10 shadow-2xl"
            />
          </div>

          {/* Hospital List Section (1/3 width on desktop) */}
          <div className="lg:col-span-1 flex flex-col gap-6">
            <div className="bg-slate-800/50 backdrop-blur-md border border-white/10 rounded-xl shadow-lg p-6 h-96 lg:h-[400px] overflow-y-auto custom-scrollbar">
              <h2 className="text-xl font-bold text-white mb-4 sticky top-0 bg-slate-800/95 p-2 -mx-2 -mt-2 rounded-t-lg z-10">{t.hospitalListTitle}</h2>
              
              <div className="space-y-4">
                {nearestHospitals.slice(0, 10).map((hospital, index) => (
                  <div
                    key={hospital.id}
                    className={`p-4 rounded-lg border cursor-pointer transition-all duration-200 ${
                      selectedHospital?.id === hospital.id
                        ? 'border-blue-500 bg-blue-500/10'
                        : 'border-white/5 hover:border-white/20 hover:bg-white/5'
                    }`}
                    onClick={() => handleHospitalSelect(hospital)}
                  >
                    <div className="flex justify-between items-start mb-2">
                      <h3 className="font-bold text-white text-sm">{hospital.name}</h3>
                      {index === 0 && userLocation && (
                        <span className="bg-green-500/20 text-green-400 text-xs px-2 py-1 rounded-full border border-green-500/20">
                          {t.nearestLabel}
                        </span>
                      )}
                    </div>
                    
                    <p className="text-xs text-slate-400 mb-1">{hospital.specialty}</p>
                    
                    {hospital.distance && (
                      <p className="text-sm font-semibold text-blue-400 mb-2">
                        {hospital.distanceText || `${hospital.distance} km away`}
                      </p>
                    )}
                    
                    <div className="flex justify-between items-center">
                      {hospital.emergency24x7 && (
                        <span className="bg-red-500/20 text-red-400 text-xs px-2 py-1 rounded-full border border-red-500/20">
                          {t.emergency24x7}
                        </span>
                      )}
                      
                      <div className="flex gap-2">
                        <a
                          href={`tel:${hospital.phone}`}
                          className="bg-green-600 text-white px-3 py-1 rounded text-xs hover:bg-green-700 transition-colors duration-200"
                          onClick={(e) => e.stopPropagation()}
                        >
                          {t.callBtn}
                        </a>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Medical Summary Sharing */}
            <div className="bg-slate-800/50 backdrop-blur-md border border-white/10 rounded-xl shadow-lg p-6 flex-1">
              <h3 className="font-bold text-white mb-4">{t.emergencyToolsTitle}</h3>
              
              <button
                onClick={handleShareMedicalSummary}
                className="w-full bg-blue-600 text-white px-4 py-3 rounded-lg font-semibold hover:bg-blue-700 transition-all duration-300 mb-3 shadow-lg shadow-blue-600/20"
              >
                📋 {t.shareMedicalSummaryBtn}
              </button>
              
              <p className="text-xs text-slate-400">
                {t.shareMedicalSummaryDesc}
              </p>
            </div>
          </div>
        </div>

        {/* Navigation */}
        <div className="text-center mt-8 space-x-4">
          <button
            onClick={() => setStage('options')}
            className="text-slate-400 hover:text-white transition-colors duration-300"
          >
            ← {t.changeOption}
          </button>
          <button
            onClick={() => navigate('/')}
            className="text-slate-400 hover:text-white transition-colors duration-300"
          >
            🏠 {t.backToHome}
          </button>
        </div>
      </div>
    </div>
  );

  // Render consent modal
  const renderConsentModal = () => (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-slate-800 border border-white/10 rounded-xl shadow-2xl max-w-md w-full p-6">
        <h3 className="text-xl font-bold text-white mb-4">{t.consentTitle}</h3>
        
        <p className="text-slate-300 mb-6">
          {t.consentDesc}
        </p>
        
        <div className="space-y-3 mb-6">
          <label className="flex items-center cursor-pointer">
            <input type="checkbox" className="mr-3 w-4 h-4 rounded border-slate-600 bg-slate-700 text-blue-600 focus:ring-blue-500" required />
            <span className="text-sm text-slate-300">
              {t.consentCheckbox1}
            </span>
          </label>
          <label className="flex items-center cursor-pointer">
            <input type="checkbox" className="mr-3 w-4 h-4 rounded border-slate-600 bg-slate-700 text-blue-600 focus:ring-blue-500" required />
            <span className="text-sm text-slate-300">
              {t.consentCheckbox2}
            </span>
          </label>
        </div>
        
        <div className="flex gap-3">
          <button
            onClick={() => setShowConsentModal(false)}
            className="flex-1 bg-slate-700 text-white px-4 py-2 rounded-lg font-semibold hover:bg-slate-600 transition-colors duration-200"
          >
            {t.cancelBtn}
          </button>
          <button
            onClick={handleConsentConfirm}
            className="flex-1 bg-blue-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-blue-700 transition-colors duration-200 shadow-lg shadow-blue-600/20"
          >
            {t.prepareSummaryBtn}
          </button>
        </div>
      </div>
    </div>
  );

  // Main render
  return (
    <>
      {stage === 'options' && renderOptionsScreen()}
      {stage === 'calling' && renderCallingScreen()}
      {stage === 'finding' && renderFindingScreen()}
      {stage === 'map-view' && renderMapView()}
      {showConsentModal && renderConsentModal()}
    </>
  );
};

export default EmergencyPage;