import { useEffect, useState } from 'react';
import { useNavigate, useOutletContext } from 'react-router-dom';
import { getLocation, sortHospitalsByDistance, detectEmergencyNumber } from '../services/locationService';
import { formatMedicalSummaryForSharing, getConsentStatus, saveConsentStatus } from '../services/emergencyService';
import MapView from '../components/MapView';
import PillLoader from '../components/PillLoader';
import hospitals from '../data/hospitals';
import { translations } from '../data/translations';

const EmergencyPage = () => {
  const navigate = useNavigate();
  const { language } = useOutletContext();
  const t = translations[language].emergency;

  const [stage, setStage] = useState('options');
  const [userLocation, setUserLocation] = useState(null);
  const [nearestHospitals, setNearestHospitals] = useState([]);
  const [locationError, setLocationError] = useState(null);
  const [isLoadingLocation, setIsLoadingLocation] = useState(false);
  const [selectedHospital, setSelectedHospital] = useState(null);
  const [showConsentModal, setShowConsentModal] = useState(false);
  const [emergencyNumber, setEmergencyNumber] = useState(null);

  useEffect(() => {
    const number = detectEmergencyNumber();
    setEmergencyNumber(number);
  }, []);

  const handleCallEmergency = () => {
    setStage('calling');
    setTimeout(() => {
      if (emergencyNumber) {
        window.location.href = `tel:${emergencyNumber.number}`;
      }
    }, 1200);
  };

  const handleFindHospitals = async () => {
    setStage('finding');
    setIsLoadingLocation(true);
    setLocationError(null);

    try {
      const locationResult = await getLocation();
      if (locationResult.success) {
        setUserLocation(locationResult.data);
        const sortedHospitals = sortHospitalsByDistance(locationResult.data, hospitals);
        setNearestHospitals(sortedHospitals);
      } else {
        setLocationError(locationResult.error);
        setNearestHospitals(hospitals);
      }
      setStage('map-view');
    } catch (error) {
      console.error('Error finding hospitals:', error);
      setLocationError(t.locationError);
      setNearestHospitals(hospitals);
      setStage('map-view');
    } finally {
      setIsLoadingLocation(false);
    }
  };

  const handleShareMedicalSummary = () => {
    const consent = getConsentStatus();
    if (consent.granted) {
      showMedicalSummary();
    } else {
      setShowConsentModal(true);
    }
  };

  const showMedicalSummary = () => {
    const summaryResult = formatMedicalSummaryForSharing();
    if (!summaryResult.success) {
      alert('No medical summary available. Please analyze a medical report first.');
      return;
    }

    const summaryWindow = window.open('', '_blank');
    summaryWindow.document.write(`
      <html>
        <head>
          <title>${t.medicalSummary}</title>
          <style>
            body { font-family: 'DM Sans', sans-serif; margin: 24px; line-height: 1.6; background-color: #f5f3ee; color: #1e3a28; }
            pre { white-space: pre-wrap; word-wrap: break-word; background-color: #fdfcf9; padding: 20px; border-radius: 12px; border: 1px solid #c8dfc9; }
            .header { color: #b91c1c; font-weight: 700; margin-bottom: 20px; font-size: 24px; }
            .disclaimer { background: #fff7ed; border: 1px solid #fdba74; color: #9a3412; padding: 12px; border-radius: 10px; margin-top: 20px; font-size: 14px; }
          </style>
        </head>
        <body>
          <div class="header">EMERGENCY MEDICAL SUMMARY</div>
          <pre>${summaryResult.data}</pre>
          <div class="disclaimer">
            <strong>DISCLAIMER:</strong> This summary is generated by AI based on previously uploaded medical reports. It assists medical professionals and does not replace clinical assessment.
          </div>
        </body>
      </html>
    `);
  };

  const handleConsentConfirm = () => {
    saveConsentStatus(true);
    setShowConsentModal(false);
    showMedicalSummary();
  };

  const renderOptionsScreen = () => (
    <section className="min-h-screen bg-[#F5F3EE] px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-4xl">
        <div className="mb-10 text-center">
          <h1 className="mb-4 text-5xl text-[#1E3A28]">Emergency Assistance</h1>
          <p className="text-lg text-[#6B8F71]">Get immediate help when you need it most</p>
        </div>

        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
          <article className="rounded-xl border-l-4 border-red-500 bg-white p-6 shadow-sm">
            <h2 className="mb-3 text-2xl text-[#1E3A28]">{t.callEmergencyServices}</h2>
            <p className="mb-6 text-[#6B8F71]">{t.callEmergencyDesc} ({emergencyNumber?.displayText || '112/911'})</p>
            <button onClick={handleCallEmergency} className="rounded-xl bg-red-600 px-6 py-3 font-medium text-white hover:bg-red-700">
              {t.callNow}
            </button>
          </article>

          <article className="rounded-xl border-l-4 border-red-500 bg-white p-6 shadow-sm">
            <h2 className="mb-3 text-2xl text-[#1E3A28]">{t.findHospitals}</h2>
            <p className="mb-6 text-[#6B8F71]">{t.findHospitalDesc}</p>
            <button onClick={handleFindHospitals} className="rounded-xl bg-red-600 px-6 py-3 font-medium text-white hover:bg-red-700">
              {t.findHospitalsBtn}
            </button>
          </article>
        </div>

        <div className="mt-8 text-center">
          <button onClick={() => navigate('/')} className="rounded-xl border border-[#3D6B4F] px-6 py-3 text-[#3D6B4F]">
            {t.backToHome}
          </button>
        </div>
      </div>
    </section>
  );

  const renderCallingScreen = () => (
    <section className="min-h-screen bg-[#F5F3EE] px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-md rounded-xl border-l-4 border-red-500 bg-white p-8 text-center shadow-sm">
        <h2 className="mb-4 text-4xl text-[#1E3A28]">{t.emergencyServicesTitle || t.title}</h2>
        <p className="mb-4 text-[#6B8F71]">{t.tapToCall}</p>
        <p className="mb-8 text-6xl font-semibold text-red-600">{emergencyNumber?.number || '112'}</p>

        <a href={`tel:${emergencyNumber?.number || '112'}`} className="inline-flex rounded-xl bg-red-600 px-6 py-3 font-medium text-white hover:bg-red-700">
          {t.callPrefix} {emergencyNumber?.number || '112'}
        </a>

        <div className="mt-8">
          <button onClick={() => setStage('options')} className="rounded-xl border border-[#3D6B4F] px-6 py-3 text-[#3D6B4F]">
            {t.cancelCall}
          </button>
        </div>
      </div>
    </section>
  );

  const renderFindingScreen = () => {
    let loadingText = t.findingHospitalsText;
    if (isLoadingLocation) loadingText = t.gettingLocation;
    if (locationError) loadingText = t.loadingHospitalData;
    return <PillLoader text={loadingText} />;
  };

  const renderMapView = () => (
    <section className="min-h-screen bg-[#F5F3EE] px-4 py-8 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl">
        <div className="mb-6 text-center">
          <h1 className="mb-2 text-4xl text-[#1E3A28]">{t.nearbyHospitalsTitle}</h1>
          <p className="text-[#6B8F71]">
            {userLocation
              ? t.foundHospitals.replace('{count}', nearestHospitals.length)
              : t.showingHospitals.replace('{count}', nearestHospitals.length)}
          </p>
          {locationError && <p className="mt-2 text-sm text-red-600">{locationError}</p>}
        </div>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          <div className="lg:col-span-2">
            <MapView
              userLocation={userLocation}
              hospitals={nearestHospitals.slice(0, 15)}
              onHospitalSelect={setSelectedHospital}
              selectedHospital={selectedHospital}
              className="h-96 rounded-xl lg:h-[600px]"
            />
          </div>

          <div className="space-y-6 lg:col-span-1">
            <div className="h-96 overflow-y-auto rounded-xl border-l-4 border-red-500 bg-white p-6 shadow-sm lg:h-[400px]">
              <h2 className="mb-4 text-2xl text-[#1E3A28]">{t.hospitalListTitle}</h2>
              <div className="space-y-4">
                {nearestHospitals.slice(0, 10).map((hospital, index) => (
                  <article
                    key={hospital.id}
                    className={`rounded-xl border p-4 transition-colors ${
                      selectedHospital?.id === hospital.id
                        ? 'border-[#3D6B4F] bg-[#E8F2E9]'
                        : 'border-[#C8DFC9] bg-[#FDFCF9]'
                    }`}
                    onClick={() => setSelectedHospital(hospital)}
                  >
                    <div className="mb-2 flex items-start justify-between gap-2">
                      <h3 className="text-sm font-semibold text-[#1E3A28]">{hospital.name}</h3>
                      {index === 0 && userLocation && (
                        <span className="rounded-full bg-[#E8F2E9] px-2 py-1 text-xs text-[#2A4A35]">{t.nearestLabel}</span>
                      )}
                    </div>

                    <p className="text-xs text-[#6B8F71]">{hospital.specialty}</p>
                    {hospital.distance && (
                      <p className="mt-1 text-xs font-semibold text-[#2A4A35]">{hospital.distanceText || `${hospital.distance} km away`}</p>
                    )}

                    <div className="mt-3 flex items-center justify-between">
                      {hospital.emergency24x7 && (
                        <span className="rounded-full bg-red-50 px-2 py-1 text-xs text-red-700">{t.emergency24x7}</span>
                      )}
                      <a
                        href={`tel:${hospital.phone}`}
                        className="rounded-xl bg-red-600 px-4 py-2 text-xs text-white hover:bg-red-700"
                        onClick={(event) => event.stopPropagation()}
                      >
                        {t.callBtn}
                      </a>
                    </div>
                  </article>
                ))}
              </div>
            </div>

            <div className="rounded-xl border-l-4 border-red-500 bg-white p-6 shadow-sm">
              <h3 className="mb-4 text-2xl text-[#1E3A28]">{t.emergencyToolsTitle}</h3>
              <button
                onClick={handleShareMedicalSummary}
                className="rounded-xl bg-red-600 px-6 py-3 font-medium text-white hover:bg-red-700"
              >
                {t.shareMedicalSummaryBtn}
              </button>
              <p className="mt-3 text-sm text-[#6B8F71]">{t.shareMedicalSummaryDesc}</p>
            </div>
          </div>
        </div>

        <div className="mt-8 flex flex-wrap justify-center gap-4">
          <button onClick={() => setStage('options')} className="rounded-xl border border-[#3D6B4F] px-6 py-3 text-[#3D6B4F]">
            {t.changeOption}
          </button>
          <button onClick={() => navigate('/')} className="rounded-xl border border-[#3D6B4F] px-6 py-3 text-[#3D6B4F]">
            {t.backToHome}
          </button>
        </div>
      </div>
    </section>
  );

  const renderConsentModal = () => (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="w-full max-w-md rounded-xl border-l-4 border-red-500 bg-white p-6 shadow-sm">
        <h3 className="mb-4 text-2xl text-[#1E3A28]">{t.consentTitle}</h3>
        <p className="mb-6 text-[#6B8F71]">{t.consentDesc}</p>

        <div className="mb-6 space-y-3">
          <label className="flex items-center gap-3">
            <input type="checkbox" className="h-4 w-4" required />
            <span className="text-sm text-[#2A4A35]">{t.consentCheckbox1}</span>
          </label>
          <label className="flex items-center gap-3">
            <input type="checkbox" className="h-4 w-4" required />
            <span className="text-sm text-[#2A4A35]">{t.consentCheckbox2}</span>
          </label>
        </div>

        <div className="flex gap-3">
          <button
            onClick={() => setShowConsentModal(false)}
            className="rounded-xl border border-[#3D6B4F] px-6 py-3 text-[#3D6B4F]"
          >
            {t.cancelBtn}
          </button>
          <button
            onClick={handleConsentConfirm}
            className="rounded-xl bg-red-600 px-6 py-3 font-medium text-white hover:bg-red-700"
          >
            {t.prepareSummaryBtn}
          </button>
        </div>
      </div>
    </div>
  );

  return (
    <>
      {stage === 'options' && renderOptionsScreen()}
      {stage === 'calling' && renderCallingScreen()}
      {stage === 'finding' && renderFindingScreen()}
      {stage === 'map-view' && renderMapView()}
      {showConsentModal && renderConsentModal()}
    </>
  );
};

export default EmergencyPage;
